### ISSUE TITLE
Changing email address of a local user fails when using the address of a previously deleted user.

### ISSUE THREAD

**Issue by brian-emery** [SpiderOak/netkes#192]
A privatecloud customer is running into an issue when attempting to change the email address of a local user to the address that was previously used by a deleted local user. Attempting to change the address results in a 500 error in the web interface and this error in the admin_console log:

```
2015-03-24 12:47:14,291 ERROR   django.request : Internal Server Error: /users/testuser2@spideroak.com/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/openmanage/django/apps/blue_management/blue_mgnt/views/views.py", line 471, in new_fun
    request.session['username'], *args, **kwargs)
  File "/opt/openmanage/django/apps/blue_management/blue_mgnt/views/users.py", line 422, in user_detail
    password.update_email(data['email'])
  File "/opt/openmanage/django/apps/openmanage/models.py", line 13, in update_email
    [new_email, self.email])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
IntegrityError: duplicate key value violates unique constraint "passwords_pkey"
DETAIL:  Key (email)=(testuser1@spideroak.com) already exists.
```

However, creating a new local user with the address succeeds without issue.

**Comment by reneelynn** [comment]
This is true in Blue SMB as well (using my Burbank test account). For reference, changing an existing account to an email that has never been used in the MC does work.

**Comment by reneelynn** [comment]
Still getting 500 Server Error on this one

**Comment by reneelynn** [comment]
bdzim was having a hard time finding the error which appears to be becasue even though I got a 500 server error it did ultimately work I had changed “renee+raptor11...” to “renee+raptor14...." and got a 500 server error but looking through my user list “renee+raptor14” exists and “renee+raptor11” does not

I tried to reproduce again anyway and it is working now changing “renee+raptor8” to both “renee+raptor11” and “renee+test15” so it must have been something else that caused the error

**Comment by brian-emery** [comment]
I believe this is resolved. Closing.
