### ISSUE TITLE
Using the command line

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/netkes#221]
## Description 
https://spideroak.com/faq/questions/1017/how_do_i_set_up_a_new_user_from_the_commandline/

## Steps to reproduce issue 
try with assigned password and also with auth codes

## Expected result 
example format with file named `claire.txt`:
{
	"username": "renee+em@spideroak.com",
	"password": "wVu4qep5MHZjzLmAyb8cOAc7J2ZQe9eLlV2Hdomc",
	"reinstall": false,
	"device_name": "Emelia test",
	"password_hint": "so sad"
}

Note that example case has false input and will not work. 

Make sure: 1) it's in plain text (Format>Make Plain Txt) you reference the full filename in ` /Applications/SpiderOakBlue.app/Contents/MacOS/SpiderOakBlue --setup=/Users/renee/Desktop/claire.txt`

## Actual result 
Fails with no terminal output, no device added in either a reinstall or new device case.

## Other information 
Reported by: Renee Jackson 

Test case number: TC50 

Test run: [http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97705#executed_case_7722385](http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97705#executed_case_7722385)

**Comment by bdzim** [comment]
Is this different from past versions of the management console? Looks like a client issue to me.

**Comment by reneelynn** [comment]
This has definitely worked in past versions :/

**Comment by bdzim** [comment]
What output do you get from a past version of the management console?

**Comment by brian-emery** [comment]
It looks like you're missing the fingerprint (although it should give you an error if you run it without the fingerprint). I tested with a similar file (just changed the username and included the fingerprint from my OMVA) and it worked. However, this was on Windows. I don't have a Mac to test with.

**Comment by reneelynn** [comment]
While (embarrassingly) it is true that I left out the fingerprint, it still fails silently with one.

**Comment by reneelynn** [comment]
*working on getting access to Rebecca's MC so I can test with an older version. I still suspect it's a client problem but it begs the question when this broke.

**Comment by reneelynn** [comment]
2015-07-20 10:56:36,183 INFO     update_schema        running update 00008_hybrid_tss
2015-07-20 10:56:36,197 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,199 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,201 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,203 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,206 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,208 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,211 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,213 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,215 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,218 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,220 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,223 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,226 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,229 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,232 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,234 INFO     SQLiteHybridTransaction commit: 0 post deletes
2015-07-20 10:56:36,236 INFO     backend              Account.load() -- cannot find state/install.dat
2015-07-20 10:56:36,236 DEBUG    main                 local user data not found or corrupt, entering nus mode
2015-07-20 10:56:36,237 INFO     get_proxy_for_url    Using proxy returned via 'disabled' method: None
2015-07-20 10:56:36,237 DEBUG    twisted              Starting factory <HTTPClientFactory: https://api.spideroak.com/setup/hello>
2015-07-20 10:56:36,240 ERROR    twisted              Unhandled error in Deferred:
2015-07-20 10:56:36,241 ERROR    twisted              Unhandled Error
Traceback (most recent call last):
  File "twisted/internet/base.pyc", line 1158, in run
    
  File "twisted/internet/base.pyc", line 1167, in mainLoop
    
  File "twisted/internet/base.pyc", line 789, in runUntilCurrent
    
  File "twisted/internet/defer.pyc", line 1141, in unwindGenerator
    
--- <exception caught here> ---
  File "twisted/internet/defer.pyc", line 1020, in _inlineCallbacks
    
  File "spider/Spider.pyc", line 389, in _start_spider
    
  File "spider/cmdline/__init__.pyc", line 335, in handle_commandline
    
  File "spider/cmdline/option_handlers/setup_handler.pyc", line 257, in try_to_handle
    
  File "spider/cmdline/option_handlers/setup_handler.pyc", line 230, in _setup_account_from_definition
    
exceptions.IOError: [Errno 13] Permission denied: '/Users/renee/Desktop/adduser.txt'

2015-07-20 10:56:36,241 DEBUG    twisted              Main loop terminated.
2015-07-20 10:56:36,241 DEBUG    port file            Removing port files
2015-07-20 10:56:36,241 INFO     main                 Program terminates

**Comment by brian-emery** [comment]
Looks like a permission problem with the file. How did you create it? If you change the permissions:

chmod 666 /Users/renee/Desktop/adduser.txt

And then try running the setup, what do you get?

**Comment by reneelynn** [comment]
curiously I get permission denied with the `chmod` command. I just created a plaintext .txt in textedit... which is my usual method for this test. Just verified that ALL the same credentials work when using just --setup=-

**Comment by merickson** [comment]
This is still a client problem, but I agree with Brian, it looks like a permissions problem on your end.
